spring.application.name=${SPRING_APPLICATION_NAME:ecommerce}


# application.properties
spring.datasource.url=jdbc:mysql://localhost:3307/solartp
spring.datasource.username=root
spring.datasource.password=Hit@My5QL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


spring.security.oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:707353335287-iqf6miqalqt8d631q468fr2clnqpljc0.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: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}

jwt.secret=4XKjK9AL/B0qX2msu3FIC4udzH+V2MsGg7TTPKbafbo=
jwt.expiration=${JWT_EXPIRATION:86400}

spring.cache.type=${SPRING_CACHE_TYPE:redis}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.redis.time-to-live=${SPRING_REDIS_TIME_TO_LIVE:600000}

uploads.path=./uploads

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:hthuongtn2905@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

app.frontend.url=${FRONTEND_URL:https://solartp.com.vn}


cloudflare.bucket-name=${CLOUD_FLARE_LINK_BUCKET_NAME:solar-images}
cloudflare.access-key=${CLOUDFLARE_ACCESS_KEY:84b2f732fdde6bf5656bc3fe3faaeee2}
cloudflare.secret-key=${CLOUDFLARE_SECRET_KEY:7725651b6f30d52f07af1a0438ef0f28d0b205176e4e6a98740413d82c56c38f}
cloudflare.endpoint=${CLOUDFLARE_ENDPOINT:https://19a38cdd9a177b0f9ecaa5c0d475533c.r2.cloudflarestorage.com}
link_image_get=${LINK_IMAGE_GET:https://pub-3df5bcdfa28f404faf4edd278e17bbf5.r2.dev/}

server.address=0.0.0.0
server.port=8080

spring.profiles.active=default
