version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  app:
    image: markus2905/solartp:latest   # Image từ Docker Hub
    container_name: spring-boot-container
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge